---
title: "Preliminary analyses - Individuals"
author: "M. Vaz"
date: "February 3, 2017"
output: html_document
---

# Basic stats
```{r,echo=FALSE}

raw2 = read.csv("raw2.csv",header=T,as.is=T)
paste("number of trees sampled: ",nrow(raw2)) # number of trees sampled

# correct crown major and minor diameters
tmp = cbind(raw2$cd1/100,raw2$cd2/100)
raw2$cd1c = apply(tmp,1,max)
raw2$cd2c = apply(tmp,1,min)

# estimates crown density
raw2$cDens = raw2$dL/raw2$cTh

# crown shape (roundness)
raw2$cSh = raw2$cd2c/raw2$cd1c

```

# Biomass and growth
```{r}

hist(raw2$bM0n)
hist(raw2$bM1n)
hist(raw2$bM0c)
hist(raw2$bM1c)

plot(c(raw2$bM0n,raw2$bM1n),xlim=c(0,3),type="n",log="y",ylab="Biomass (kg)",xaxt="n",xlab="Census",main="Without wood density")
for(i in 1:nrow(raw2)){points(x=c(.5,2.5),y=c(raw2$bM0n[i],raw2$bM1n[i]),type="b",pch=16,col=grey(0.5,0.5))}
tmp = subset(raw2,bM0n>bM1n)
for(i in 1:nrow(tmp)){points(x=c(.5,2.5),y=c(tmp$bM0n[i],tmp$bM1n[i]),type="b",pch=16,col=rainbow(1,alpha=.2))}
nrow(tmp)

plot(c(raw2$bM0c,raw2$bM1c),xlim=c(0,3),type="n",log="y",ylab="Biomass (kg)",xaxt="n",xlab="Census",main="With wood density")
for(i in 1:nrow(raw2)){points(x=c(.5,2.5),y=c(raw2$bM0c[i],raw2$bM1c[i]),type="b",pch=16,col=grey(0.5,0.5))}
tmp = subset(raw2,bM0c>bM1c)
for(i in 1:nrow(tmp)){points(x=c(.5,2.5),y=c(tmp$bM0c[i],tmp$bM1c[i]),type="b",pch=16,col=rainbow(1,alpha=.2))}
nrow(tmp)

hist(raw2$rgrD);sum(raw2$rgrD<0,na.rm=T)
hist(raw2$rgrBn);sum(raw2$rgrBn<0,na.rm=T)
hist(raw2$rgrBc);sum(raw2$rgrBc<0,na.rm=T)

plot(log(raw2$bM0c),log(raw2$bM1c))
mod = lm(log(raw2$bM1c)~log(raw2$bM0c))
summary(mod)
text(1,-1.5,expression(paste(R^2,"=0.55***")),col=2)
abline(mod,col=2)

plot(log(raw2$bM0c),log(raw2$rgrBc))
mod = lm(log(raw2$rgrBc)~log(raw2$bM0c))
summary(mod)
text(1.5,-4,expression(paste(R^2,"=0.27***")),col=2)
abline(mod,col=2)


```

# Crown height and position
```{r,echo=FALSE}

hist(raw2$cmax/100+1.4,main="Crown",xlab="Top height (m)")
hist(raw2$cmean/100+1.4,main="Crown",xlab="Mean height (m)")
hist(raw2$cmin/100+1.4,main="Crown",xlab="Bottom height (m)")

hist(raw2$cTh,main="Crown",xlab="Thickness (m)")
hist(raw2$RcTh,main="Crown",xlab="Relative thickness (%)")
hist(raw2$RcPos,main="Crown",xlab="Relative position (%)")

plot(raw2$cmax/100+1.4,raw2$cmin/100+1.4,xlab="Top height (m)",ylab="Mean/Bottom height (m)",main="Crown");abline(a=0,b=1)
points(raw2$cmax/100+1.4,raw2$cmean/100+1.4,col=grey(0.5,0.5),pch=16)

plot(raw2$cmax/100+1.4,raw2$cTh,xlab="Top height (m)",ylab="Thickness (m)",main="Crown")
plot(raw2$cmax/100+1.4,raw2$RcTh,xlab="Top height (m)",ylab="Relative thickness (m)",main="Crown")
plot(raw2$cmax/100+1.4,raw2$RcPos,xlab="Top height (m)",ylab="Relative position (%)",main="Crown")

#plot(raw2$cTh,raw2$RcTh,xlab="Thickness (m)",ylab="Relative thickness (%)",main="Crown")
#plot(raw2$cmean/100+1.4,raw2$RcPos,xlab="Mean height (m)",ylab="Relative position (%)",main="Crown")

```

# Crown shape, projected area and volume
```{r,echo=FALSE}

hist(raw2$cd1c,main="Crown",xlab="Longest diameter (m)")
hist(raw2$cd2c,main="Crown",xlab="Longest perpendicular diameter (m)")
hist(raw2$cSh,main="Crown",xlab="Roundness")

plot(raw2$cd1c,raw2$cd2c,xlab="Major diameter (m)",ylab="Minor diameter (m)",main="Crown shape");abline(a=0,b=1)

hist(raw2$cArea,main="Crown",xlab="Area (m^2)")

plot(raw2$cmax/100+1.4,raw2$cArea,main="Crown",xlab="Top height (m)",ylab="Area (m^2)")
plot(raw2$cTh,raw2$cArea,main="Crown",xlab="Thickness (m)",ylab="Area (m^2)",log="y")

#hist(raw2$cVol,main="Crown",xlab="Cylinder volume (cm^3)")
hist(raw2$cVol2,main="Crown",xlab="Double cone volume (cm^3)")

#plot(raw2$cVol,raw2$cVol2,xlab="Cylinder volume (cm^3)",ylab="Double cone volume (cm^3)",main="Crown")
plot(raw2$cSh,raw2$cVol2,xlab="Roundness",ylab="Volume (cm^3)",main="Crown")
plot(raw2$cmax/100+1.4,raw2$cVol2,xlab="Top height (m)",ylab="Volume (cm^3)",main="Crown")

```

# Light interception
```{r,echo=FALSE}

hist(raw2$dL,main="Crown",xlab="light attenuation (%)")

hist(raw2$cDens,main="Crown",xlab="Density (light attenuation (%) m^-1)")

plot(raw2$cTh,raw2$dL,xlab="Thickness (m)",ylab="Light attenuation (%)",main="Crown density")

plot(raw2$cArea,raw2$dL,xlab="Area (m^2)",ylab="Light attenuation (%)",main="Crown",log="x")
#plot(raw2$cArea,raw2$cDens,xlab="Area (m^2)",ylab="Density (light attenuation (%) m^-1)",main="Crown",log="xy")
plot(raw2$cmax/100+1.4,raw2$dL,xlab="Top height (m)",ylab="Light attenuation (%)",main="Crown",log="x")
#plot(raw2$cSh,raw2$dL,xlab="Roundness",ylab="Light attenuation (%)",main="Crown")
plot(raw2$cVol2,raw2$dL,xlab="Volume (cm^3)",ylab="Light attenuation (%)",main="Crown",log="x")

```

# Light conditions
```{r,echo=F}

hist(raw2$cii,main="",xlab="Crown ilumination index")

plot(raw2$cii,raw2$dL,xlab="Crown ilumination index",ylab="Light interception (%)")
plot(raw2$cii,raw2$cVol2,xlab="Crown ilumination index",ylab="Crown volume (m^3)")
plot(raw2$cii,raw2$RcTh,xlab="Crown ilumination index",ylab="Relative crown thickness (%)")
plot(raw2$cii,raw2$RcPos,xlab="Crown ilumination index",ylab="Relative crown position (%)")
plot(raw2$cii,raw2$cArea,xlab="Crown ilumination index",ylab="Crown area (m^2)")
plot(raw2$cii,raw2$cSh,xlab="Crown ilumination index",ylab="Crown roundness")
plot(raw2$cii,raw2$taper,xlab="Crown ilumination index",ylab="Relative crown thickness (%)")


```

# Stem height, tapering, volume, density and mass
```{r,echo=FALSE}

hist(raw2$sh/100+1.4,main="Stem",xlab="Height (m)")
hist(raw2$taper,main="Stem",xlab="Tapering (mm m^-1)")

plot(raw2$sh/100+1.4,abs(raw2$taper),main="Stem",xlab="Height (m)",ylab="Tapering (mm m^-1)",log="xy")

hist(raw2$sVol,main="Stem",xlab="Volume (mm^3)")
hist(raw2$sDens,main="Stem",xlab="Estimated density (g cm^-3)")
hist(raw2$sMass,main="Stem",xlab="Estimated mass (g)")

plot(raw2$sDens,raw2$dL,main="Stem",xlab="Density (g cm^-3)",ylab="Intercepted light (%)")
plot(x=raw2$sDens,abs(raw2$taper),main="Stem",xlab="Density (g cm^-3)",ylab="Tapering (mm m^-1)",log="y")
plot(y=raw2$dL,abs(raw2$taper),main="Stem",ylab="Intercepted light (%)",xlab="Tapering (mm m^-1)",log="x")

```

# PCA
```{r,echo=FALSE}

bv = c("sh","cmax","cmean","cmin","cd1","cd2","sDens","taper","dL","cii")
dd0 = na.omit(raw2[,bv])
dd = scale(dd0[,-ncol(dd0)])

pca = prcomp(dd)
summary(pca)
ss = predict(pca)

plot(pca$sdev^2*100/sum(pca$sdev^2),type="b",xlab="PC",ylab="Variance explained (%)")

source("biplot.R")
biplot(pca,1:2,7,.1)
biplot(pca,3:4,2,.1)


# Plot PCs against light conditions
plot(ss[,1],x=dd0$cii)
plot(ss[,2],x=dd0$cii)

```

# Partial regression
```{r, echo=F}

tmp = subset(raw2,select=c("cmax","tL","bM1c","rgrBc","bM0c","LUEc","LIEc","sp"))
tmp$cmax = tmp$cmax/100+1.4
tmp = na.omit(tmp)
tmp = tmp[which(tmp$rgrBc>=0),]
nrow(tmp)
head(tmp)

# HGE
plot(y=tmp$cmax,tmp$bM1c,xlab="Estimated biomass (kg)",ylab="Height (m)")
plot(y=log(tmp$cmax),log(tmp$bM1c),xlab="log Estimated biomass (kg)",ylab="log Height (m)")
hb = lm(log(tmp$cmax)~log(tmp$bM1c))
abline(hb,col=2)
summary(hb)
text(-1.7,2,expression(paste(R^2,"=0.46")),col=2)

# LIE
plot(y=tmp$tL,tmp$bM1c,xlab="Estimated biomass (kg)",ylab="Estimated light interception")
plot(y=log(tmp$tL),log(tmp$bM1c),xlab="log Estimated biomass (kg)",ylab="log Estimated light interception")
lb = lm(log(tmp$tL)~log(tmp$bM1c))
abline(lb,col=2)
summary(lb)
text(-1.7,6,expression(paste(R^2,"=0.22")),col=2)

# LIE x HGE
plot(x=hb$residuals,lb$residuals,xlab="Height-biomass residuals",ylab="Light-biomass residuals")
hlb = lm(lb$residuals~hb$residuals)
#abline(hlb,col=2)
summary(hlb)

# LUE
plot(log(tmp$rgrBc),x=log(tmp$tL),xlab="Light intercepted",ylab="RGR")
gl = lm(log(tmp$rgrBc)~log(tmp$tL))
abline(gl,col=2)
summary(gl)
text(.5,-1,expression(paste(R^2,"=0.03")))


# LUE x LIE - SMA
library(smatr)
source("regr.plot.R")
mod = sma(log(tmp$LUEc)~log(tmp$LIEc))
regr.plot(mod)
subset(raw2,LIEc<1,select="sp")
subset(raw2,LIEc>exp(6),select="sp")

# LUE x LIE - Residuals
plot(lb$residuals,y=gl$residuals,xlab="LIE",ylab="LUE")
ll = lm(gl$residuals~lb$residuals)
summary(ll)

# LUE x LIE - Permutation test
obs = cor(log(tmp$LUEc),log(tmp$LIEc))
cor.test(log(tmp$LUEc),log(tmp$LIEc))

res = numeric()
for(i in 1:9999){
  tmptL = sample(tmp$tL)
  res[i] = cor(log((tmp$bM1c-tmp$bM0c)/tmptL),log(tmptL/tmp$bM1c))
}
res = c(res,obs)
pp = sum(res<obs)/10000

hist(res,xlab="Pearson's R",main="Permutation test")
abline(v=quantile(res,.05),col=2,lty=3)
arrows(obs,100,obs,0,col=4,length=.1)
legend(x="topright",c("R","=",round(obs,2),"","p","=",pp),bty="n",text.col=2)


# Fit SMA for each species
plot(y=log(tmp$LUEc),x=log(tmp$LIEc),pch=16,col=grey(.5,alpha=.5))
mod = sma(log(tmp$LUEc)~log(tmp$LIEc))

sps = unique(tmp$sp)
sps = sps[which(table(tmp$sp)>2)]
sps = sps[sps!=" " & sps!="NI NI" & sps!="Manilkara ???" & sps!="Lecythis " & sps!="Manilkara " & sps!="Pouteria NI" & sps!="Pouteria " & sps!="Pouteria sp."]
sps

for(i in sps){
  tmp2 = subset(tmp,sp==i)
  mod2 = sma(log(tmp2$LUEc)~log(tmp2$LIEc))
  abline(mod2,col=grey(.5,.5))
  }
abline(mod,lwd=2)


# Next step is to consider CII and height into the light interception equation: light = crown area * light * mean crown height * crown illumination index

```

# Diagnostic plots
```{r}

# above and below crown light x height for each individual
tmp = subset(raw2,select=c("cmax","il1","il2","il3","il4","il5","tl1","tl2","tl3","tl4","tl5"))
tmp$cmax = tmp$cmax/100+1.4
tmp = tmp[order(tmp$cmax),]
tmp$above = apply(tmp[,c("il1","il2","il3","il4","il5")],1,mean)
tmp$below = apply(tmp[,c("tl1","tl2","tl3","tl4","tl5")],1,mean)
tmp$ext = tmp$below*100/tmp$above
tmp = na.omit(tmp)
tmp = subset(tmp,above>0 & below>0)
head(tmp)

plot(tmp$cmax,ylab="Height (m)")
plot(tmp$above,ylab="Incident light")
plot(tmp$below,ylab="Transmitted light")
plot(tmp$ext,ylab="Light transmitted (%)")

rr = range(tmp[,c("il1","il2","il3","il4","il5","tl1","tl2","tl3","tl4","tl5")],na.rm=T)
plot(tmp$cmax,ylab="Light",type="n",ylim=rr)
#abline(v=1:nrow(tmp),col=grey(0.1,alpha=.5),lty=3)
for(i in 1:nrow(tmp)){
  points(x=rep(i,5),y=tmp[i,c("il1","il2","il3","il4","il5")],col=rainbow(1,alpha=.5),pch=16)
  points(x=rep(i,5),y=tmp[i,c("tl1","tl2","tl3","tl4","tl5")],col=rainbow(1,start=0.5,alpha=.5),pch=16)
  }


# crown thickness/position x plant height
tmp2 = subset(raw2,select=c("cmax","cmean","cmin"))
tmp2 = na.omit(tmp2)
tmp2$cmax = tmp2$cmax/100+1.4
tmp2$cmean = tmp2$cmean/100+1.4
tmp2$cmin = tmp2$cmin/100+1.4
tmp2 = tmp2[order(tmp2$cmax),]
head(tmp2)

rr2 = range(tmp2[,c("cmax","cmean","cmin")])
plot(tmp2$cmax,ylab="Height (m)",type="n",ylim=rr2)
for(i in 1:nrow(tmp2)){
  segments(i,tmp2[i,"cmin"],i,tmp2[i,"cmax"],col=grey(0.5,alpha=0.5))
  points(i,tmp2[i,"cmean"],pch=16,cex=.5,col=grey(0.5,alpha=0.5))
  }


```






