---
title: "Preliminary analyses - Species"
author: "M. Vaz"
date: "February 3, 2017"
output: html_document
---

# Basic stats
```{r,echo=FALSE}

raw2 = read.csv("raw2.csv",header=T,as.is=T)
paste("number of species sampled: ",length(unique(raw2$sp))) # number of trees sampled

# correct crown major and minor diameters
tmp = cbind(raw2$cd1/100,raw2$cd2/100)
raw2$cd1c = apply(tmp,1,max)
raw2$cd2c = apply(tmp,1,min)

# estimates crown density
raw2$cDens = raw2$dL/raw2$cTh

# crown shape (roundness)
raw2$cSh = raw2$cd2c/raw2$cd1c

# calculate means for each species
mm = aggregate(cbind(cmax,tL,bM1c,bM0c,sDens,RcTh,RcPos,tL,taper,HGE,rgrBc,LIEc,LUEc,cDens,cSh,Hmax)~sp,raw2,mean,na.rm=T,na.action=NULL)
head(mm)

```

# Architecture: crown and stem
```{r,echo=FALSE}

plot(mm$sDens,mm$tL,xlab="Stem density (g cm^3)",ylab="Light intercepted (% m^2)",main="")
mod5 = lm(mm$tL~mm$sDens)
summary(mod5)

plot(mm$HGE,mm$tL,xlab="Height gain efficiency (cm g^-1)",ylab="Light intercepted (% m^2)",main="",xlim=c(0,5))
plot(mm$HGE,mm$RcPos,xlab="Height gain efficiency (cm g^-1)",ylab="Relative crown position (%)",main="",xlim=c(0,5))
plot(mm$HGE,mm$rgrBc,xlab="Height gain efficiency (cm g^-1)",ylab="Relative crown position (%)",main="",xlim=c(0,5))

plot(log(mm$LIEc),log(mm$LUEc),xlab="log(LIE)",ylab="log(LUE)")
mod6 = lm(log(mm$LUEc)~log(mm$LIEc))
summary(mod6)
text(1,7.5,expression(paste(R^2,"= 0.52***")),col=2)
abline(mod6,col=2)
subset(mm,LUEc>exp(6))


#plot(mm[,-1])

```

# Hmax
```{r,echo=FALSE}

# Hmax x RGR
plot(mm$Hmax,mm$rgrBc,xlab="Hmax",ylab="RGR")
mod = lm(mm$rgrBc~mm$Hmax)
summary(mod)

# Hmax x sDens
plot(mm$Hmax,mm$sDens,xlab="Hmax",ylab="Stem density")
mod = lm(mm$sDens~mm$Hmax)
summary(mod)

# Hmax x HGE
plot(mm$Hmax,mm$HGE,xlab="Hmax",ylab="HGE")
mod = lm(mm$HGE~mm$Hmax)
summary(mod)
#plot(mod) # outlier
subset(raw2,HGE>6,select="sp")

plot(mm$Hmax,mm$HGE,xlab="Hmax",ylab="HGE",ylim=c(0,4))
mod = lm(subset(mm,HGE<6,select=HGE,drop=T)~subset(mm,HGE<6,select=Hmax,drop=T))
summary(mod) # without outlier
abline(mod,col=2)
text(9,4,expression(paste(R^2," = 0.04*")),col=2)

# Hmax x LIE
plot(mm$Hmax,mm$LIEc,xlab="Hmax",ylab="LIE")
mod = lm(mm$LIEc~mm$Hmax)
summary(mod)
abline(mod,col=2)
text(30,170,expression(paste(R^2," = 0.06*")),col=2)

# Hmax x LUE
plot(subset(mm,LUEc<100 & LUEc>-50,select=c("Hmax","LUEc")),xlab="Hmax",ylab="LUE")
mod = lm(subset(mm,LUEc<100 & LUEc>-50,select="LUEc",drop=T)~subset(mm,LUEc<100 & LUEc>-50,select="Hmax",drop=T))
summary(mod)
#plot(mod)

```

# PCA
```{r,echo=FALSE}

bv = c("sDens","RcTh","RcPos","RcPos","tL","HGE","rgrBc","LIEc","LUEc","cDens","cSh","Hmax")
dd = na.omit(scale(mm[,bv]))

pca = prcomp(dd[,1:(ncol(dd)-1)])
summary(pca)
ss = predict(pca)

plot(pca$sdev^2*100/sum(pca$sdev^2),type="b",xlab="PC",ylab="Variance explained (%)")

source("biplot.R")
biplot(pca,1:2,7,.1)
biplot(pca,3:4,5,.1)

plot(na.omit(dd[,"Hmax"]),ss[,1])
plot(na.omit(dd[,"Hmax"]),ss[,2])
plot(na.omit(dd[,"Hmax"]),ss[,3])
plot(na.omit(dd[,"Hmax"]),ss[,4])

```

# Partial regression
```{r,echo=FALSE}

tmp = subset(mm,LUEc>0,select=c("cmax","tL","bM1c","rgrBc","bM0c"))
tmp$cmax = tmp$cmax/100+1.4
tmp = na.omit(tmp)
tmp = tmp[which(tmp$rgrBc>=0),]

# HGE
plot(y=tmp$cmax,tmp$bM1c,xlab="Estimated biomass (kg)",ylab="Height (m)")
plot(y=log(tmp$cmax),log(tmp$bM1c),xlab="log Estimated biomass (kg)",ylab="log Height (m)")
hb = lm(log(tmp$cmax)~log(tmp$bM1c))
abline(hb,col=2)
summary(hb)
text(-1.7,1.8,expression(paste(R^2,"=0.57***")),col=2)

# LIE
plot(y=tmp$tL,tmp$bM1c,xlab="Estimated biomass (kg)",ylab="Estimated light interception")
plot(y=log(tmp$tL),log(tmp$bM1c),xlab="log Estimated biomass (kg)",ylab="log Estimated light interception")
lb = lm(log(tmp$tL)~log(tmp$bM1c))
abline(lb,col=2)
summary(lb)
text(-1.7,5.5,expression(paste(R^2,"=0.34***")),col=2)

# HGE x LIE
plot(x=hb$residuals,lb$residuals,xlab="HGE",ylab="LIE")
hlb = lm(lb$residuals~hb$residuals)
#abline(hlb,col=2)
summary(hlb)

# LUE
plot(x=tmp$tL,tmp$rgrBc,ylab="RGR",xlab="Estimated light interception")
plot(x=log(tmp$tL),log(tmp$rgrBc),ylab="log RGR",xlab="log Estimated light interception")
gl = lm(log(tmp$rgrBc)~log(tmp$tL))
abline(gl,col=2)
summary(gl)
text(1.4,-1,expression(paste(R^2,"=0.10***")),col=2)

# LIExLUE
plot(lb$residuals,y=gl$residuals,xlab="light-biomass residuals",ylab="growth-light residuals")
ll = lm(gl$residuals~lb$residuals)
summary(ll)

# LIE, HGE, LUE x Hmax - Residuals
tmp2 = subset(mm,select=c("cmax","tL","bM1c","rgrBc","Hmax","LIEc","LUEc"))
tmp2$cmax = tmp2$cmax/100+1.4
tmp2 = na.omit(tmp2)
tmp2 = tmp2[which(tmp2$rgrBc>=0),]
hb2 = lm(log(tmp2$cmax)~log(tmp2$bM1c))
lb2 = lm(log(tmp2$tL)~log(tmp2$bM1c))
gl2 = lm(log(tmp2$rgrBc)~log(tmp2$tL))

plot(tmp2$Hmax,hb2$residuals,xlab="Hmax",ylab="HGE")
summary(lm(hb2$residuals~tmp2$Hmax))

plot(tmp2$Hmax,lb2$residuals,xlab="Hmax",ylab="LIE")
summary(lm(lb2$residuals~tmp2$Hmax))

plot(tmp2$Hmax,gl2$residuals,xlab="Hmax",ylab="LUE")
summary(lm(gl2$residuals~tmp2$Hmax))


# LUE x LIE - Permutation test
tmp = subset(mm,bM1c-bM0c>0 & !is.na(tL))
nrow(tmp)
obs = cor(log((tmp$bM1c-tmp$bM0c)/tmp$tL),log(tmp$tL/tmp$bM1c))
cor.test(log((tmp$bM1c-tmp$bM0c)/tmp$tL),log(tmp$tL/tmp$bM1c))

res = numeric()
for(i in 1:9999){
  tmptL = sample(tmp$tL)
  tmpDb = sample(tmp$bM1c-tmp$bM0c)
  tmpB1 = sample(tmp$bM1c)
  res[i] = cor(log((tmpDb)/tmptL),log(tmptL/tmpB1))
  }
res = c(res,obs)
pp = sum(res<obs)/10000

hist(res,xlab="Pearson's R",main="Permutation test")
abline(v=quantile(res,.05),col=2,lty=3)
arrows(obs,500,obs,0,col=4,length=.1)
legend(x="topright",c("R","=",round(obs,2),"","p","=",pp),bty="n",text.col=2)


# LUE x LIE - SMA
library(smatr)
source("regr.plot.R")
tmp = subset(mm,!is.na(LUEc) & LUEc>0 & LUEc<300)
nrow(tmp)
mod = sma(log(tmp$LIEc)~log(tmp$LUEc))
regr.plot(mod)
cols = topo.colors(40,alpha=.7)[round(tmp$Hmax)]

plot(log(tmp$LIEc),log(tmp$LUEc),xlab="log(LIE)",ylab="log(LUE)",col=cols,pch=16)
legend(x="topright",legend=seq(5,35,5),col=topo.colors(40,alpha=.7)[seq(5,35,5)],bty="n",pch=16)

# Plot residuals from SMA against plot abundances
maxsizes = read.csv("maxsizes.csv",header=T)
maxsizes$sp = paste(maxsizes$Genus,maxsizes$epithet)
head(maxsizes)

tmp2 = subset(tmp,sp%in%maxsizes$sp)
nrow(tmp2)
row.names(maxsizes) = maxsizes$sp
tmp2$n = maxsizes[tmp2$sp,"n"]
tmp2 = tmp2[-16,]
head(tmp2)
mod2 = sma(log(tmp2$LIEc)~log(tmp2$LUEc))
regr.plot(mod2)
plot(residuals(mod2),y=log(tmp2$n),xlab="SMA residuals",ylab="Plot abundance")
mod3 = lm(log(tmp2$n)~residuals(mod2))
summary(mod3)
abline(mod3,col=2)
text(.5,2,expression(paste(R^2,"=0.05*")),col=2)


# LUE x LIE - PCA
pca = prcomp(log(tmp[,c("LUEc","LIEc")]),scale.=T)
summary(pca)
ss = predict(pca)
plot(ss[,1],ss[,2]);abline(v=0,h=0,lty=3,col="grey")
#text(c("LIE","LUE"),x=pca$rotation[,1],y=pca$rotation[,2])

plot(ss[,1]~tmp$Hmax,ylim=c(-2.5,2),xlab="Hmax",ylab="PC1")
mod = lm(ss[,1]~tmp$Hmax)
summary(mod)
abline(mod,col=2)
text(30,2,expression(paste(R^2,"=0.05*")),col=2)


```




